version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=meepshop-es
      - node.name=node-1
      - bootstrap.memory_lock=true
      - network.host=elasticsearch1
      - "discovery.zen.ping.unicast.hosts=elasticsearch2"
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=meepshop-es
      - node.name=node-2
      - bootstrap.memory_lock=true
      - network.host=elasticsearch2
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - discovery.zen.minimum_master_nodes=2
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    restart: always
    networks:
      - esnet
  # elasticsearch3:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
  #   container_name: elasticsearch3
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - cluster.name=meepshop-es
  #     - node.name=node-3
  #     - bootstrap.memory_lock=true
  #     - network.host=elasticsearch3
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2"
  #     - discovery.zen.minimum_master_nodes=2
  #     - xpack.security.enabled=false
  #     - xpack.monitoring.enabled=true
  #     - xpack.graph.enabled=false
  #     - xpack.watcher.enabled=false
  #     - xpack.ml.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 2g
  #   volumes:
  #     - esdata3:/usr/share/elasticsearch/data
  #   ports:
  #     - 9202:9200
  #   restart: always
  # networks:
  #     - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    container_name: kibana
    environment:
      - SERVER_PORT=5601
      - SERVER_HOST=kibana
      - ELASTICSEARCH_URL=http://elasticsearch1:9200
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.graph.enabled=false
      - xpack.reporting.enabled=false
      - xpack.ml.enabled=false
    ports:
      - 5601:5601
    restart: always
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  # esdata3:
  #   driver: local

networks:
  esnet:
